window.CITY={id:"birmingham",name:"Birmingham",region:"the West Midlands",mapCenter:[52.4797,-1.9027],mapZoom:12,texts:{
 flowCredit:"ORR Estimates of Station Usage 2024-25 (National Rail); day-of-week split modelled",
 police:"West Midlands Police",
 voaYear:"Mar 2025",
 voaMethod:`<p>Rateable value per m² for retail and office stock by billing authority, Valuation Office Agency business floorspace statistics, 31 March 2025.</p>`,
 crimeNote:"Source: West Midlands Police recorded offences around the anchor, via data.police.uk. A relative signal between areas, not an absolute risk figure.",
 movement:`<p>Typical-day station entries and exits by day type (Mon / Tue-Thu / Fri / Sat / Sun) and annual totals from ORR Estimates of Station Usage 2024-25 for every National Rail station in the West Midlands, summed over the stations named for each segment. ORR publishes annual totals only, so the day-of-week split is MODELLED on a standard GB rail week profile (median London Overground profile) and labelled as such; the annual total stays OBSERVED. Stations within 900 m from OpenStreetMap. Street-level pitches inherit their parent catchment's counts scaled to the street's share of recorded commercial units (marked MODELLED); streets beyond 900 m of any station show no flow at all. Tram/metro stops carry no open stop-level counts, so tram flow is not an anchor in this city.</p>`,
 crimeMethod:`<p>West Midlands Police recorded street-level offences within ~450 m of each segment anchor, 12 months to July 2026: shoplifting, theft from the person, robbery and burglary, via data.police.uk. Rates are normalised per 1,000 residents.</p>`,
 crimeDropped:"",
 coverage:(SEGS,UNITS)=>`<p>${SEGS.length.toLocaleString("en-GB")} segments covering the West Midlands at street level: ${SEGS.filter(s=>s.lvl!=="street").length} area pitches (every National Rail station catchment in the West Midlands plus curated commercial areas - ORR Estimates of Station Usage 2024-25, no minimum flow) and ${SEGS.filter(s=>s.lvl==="street").length.toLocaleString("en-GB")} street pitches - every named retail street and parade with 8 or more recorded commercial units, long streets split into roughly 400 m stretches. ${UNITS.length.toLocaleString("en-GB")} individual commercial units recorded across them. A street pitch inside a station catchment carries that catchment's flow MODELLED down to the street's share of recorded units; a street more than 900 m from any station has no flow anchor and says so on its panel.</p>`,
}};