# Station catchment segments added in the all-of-London expansion (TfL AC2025 + ORR NR).
# anchors mode tag: AC = TfL Annual Station Counts 2025, ORR = ORR Estimates of Station Usage 2024-25.
NEW_SEGMENTS = [
 dict(id='moorgate', name='Moorgate station area', borough='City of London', zone='Zone 1', lat=51.51825, lng=-0.08906, stype='transport_hub', anchors=[('Moorgate', 'AC')]),
 dict(id='east-croydon', name='East Croydon station area', borough='Croydon', zone='Outside zones 1-9', lat=51.37584, lng=-0.09273, stype='transport_hub', anchors=[('East Croydon', 'ORR')]),
 dict(id='westminster', name='Westminster station area', borough='Westminster', zone='Zone 1', lat=51.50136, lng=-0.12493, stype='transport_hub', anchors=[('Westminster', 'AC')]),
 dict(id='gloucester-road', name='Gloucester Road station area', borough='Kensington and Chelsea', zone='Zone 1', lat=51.49453, lng=-0.18377, stype='transport_hub', anchors=[('Gloucester Road', 'AC')]),
 dict(id='shenfield', name='Shenfield station area', borough='Brentwood', zone='Outside zones 1-9', lat=51.63088, lng=0.32985, stype='transport_hub', anchors=[('Shenfield', 'AC')]),
 dict(id='marylebone', name='Marylebone station area', borough='Westminster', zone='Zone 1', lat=51.52224, lng=-0.16351, stype='transport_hub', anchors=[('Marylebone LU', 'AC')]),
 dict(id='pimlico', name='Pimlico station area', borough='Westminster', zone='Zone 1', lat=51.48916, lng=-0.13533, stype='transport_hub', anchors=[('Pimlico', 'AC')]),
 dict(id='city-thameslink', name='City Thameslink station area', borough='City of London', zone='Zone 1', lat=51.51513, lng=-0.10356, stype='transport_hub', anchors=[('City Thameslink', 'ORR')]),
 dict(id='surbiton', name='Surbiton station area', borough='Kingston upon Thames', zone='Zone 6', lat=51.39241, lng=-0.304, stype='transport_hub', anchors=[('Surbiton', 'ORR')]),
 dict(id='watford-junction', name='Watford Junction station area', borough='Watford', zone='Outside zones 1-9', lat=51.66391, lng=-0.39593, stype='transport_hub', anchors=[('Watford Junction', 'AC')]),
 dict(id='bromley-south', name='Bromley South station area', borough='Bromley', zone='Zone 5', lat=51.40004, lng=0.01828, stype='transport_hub', anchors=[('Bromley South', 'ORR')]),
 dict(id='great-portland-street', name='Great Portland Street station area', borough='Westminster', zone='Zone 1', lat=51.52381, lng=-0.1437, stype='transport_hub', anchors=[('Great Portland Street', 'AC')]),
 dict(id='putney', name='Putney station area', borough='Wandsworth', zone='Zones 2/3', lat=51.46093, lng=-0.21535, stype='transport_hub', anchors=[('Putney', 'ORR')]),
 dict(id='earlsfield', name='Earlsfield station area', borough='Wandsworth', zone='Zone 3', lat=51.4424, lng=-0.18769, stype='transport_hub', anchors=[('Earlsfield', 'ORR')]),
 dict(id='swiss-cottage', name='Swiss Cottage station area', borough='Camden', zone='Zone 2', lat=51.54372, lng=-0.17498, stype='transport_hub', anchors=[('Swiss Cottage', 'AC')]),
 dict(id='colindale', name='Colindale station area', borough='Barnet', zone='Zone 4', lat=51.59541, lng=-0.24993, stype='transport_hub', anchors=[('Colindale', 'AC')]),
 dict(id='west-brompton', name='West Brompton station area', borough='Kensington and Chelsea', zone='Zone 2', lat=51.48698, lng=-0.19518, stype='transport_hub', anchors=[('West Brompton', 'AC')]),
 dict(id='west-ham', name='West Ham station area', borough='Newham', zone='Zones 2/3', lat=51.5281, lng=0.00457, stype='transport_hub', anchors=[('West Ham', 'AC')]),
 dict(id='orpington', name='Orpington station area', borough='Bromley', zone='Zone 6', lat=51.3736, lng=0.08872, stype='transport_hub', anchors=[('Orpington', 'ORR')]),
 dict(id='twickenham', name='Twickenham station area', borough='Richmond upon Thames', zone='Zone 5', lat=51.45058, lng=-0.32884, stype='transport_hub', anchors=[('Twickenham', 'ORR')]),
 dict(id='sutton-london', name='Sutton station area', borough='Sutton', zone='Zone 5', lat=51.35968, lng=-0.19089, stype='transport_hub', anchors=[('Sutton (London)', 'ORR')]),
 dict(id='putney-bridge', name='Putney Bridge station area', borough='Hammersmith and Fulham', zone='Zone 2', lat=51.4683, lng=-0.2088, stype='transport_hub', anchors=[('Putney Bridge', 'AC')]),
 dict(id='cannon-street', name='Cannon Street station area', borough='City of London', zone='Zone 1', lat=51.51138, lng=-0.09036, stype='transport_hub', anchors=[('Cannon Street LU', 'AC')]),
 dict(id='kingston', name='Kingston station area', borough='Kingston upon Thames', zone='Zone 6', lat=51.41293, lng=-0.30182, stype='transport_hub', anchors=[('Kingston', 'ORR')]),
 dict(id='maryland', name='Maryland station area', borough='Newham', zone='Zone 3', lat=51.54612, lng=0.00638, stype='transport_hub', anchors=[('Maryland', 'AC')]),
 dict(id='caledonian-road', name='Caledonian Road station area', borough='Islington', zone='Zone 2', lat=51.54848, lng=-0.11836, stype='transport_hub', anchors=[('Caledonian Road', 'AC')]),
 dict(id='westferry', name='Westferry station area', borough='Tower Hamlets', zone='Zone 2', lat=51.5094, lng=-0.02664, stype='transport_hub', anchors=[('Westferry', 'AC')]),
 dict(id='south-quay', name='South Quay station area', borough='Tower Hamlets', zone='Zone 2', lat=51.50004, lng=-0.01625, stype='transport_hub', anchors=[('South Quay', 'AC')]),
 dict(id='wandsworth-town', name='Wandsworth Town station area', borough='Wandsworth', zone='Zone 2', lat=51.46096, lng=-0.18825, stype='transport_hub', anchors=[('Wandsworth Town', 'ORR')]),
 dict(id='stratford-international-dlr', name='Stratford International DLR station area', borough='Newham', zone='Zones 2/3', lat=51.54525, lng=-0.00905, stype='transport_hub', anchors=[('Stratford International DLR', 'AC')]),
 dict(id='feltham', name='Feltham station area', borough='Hounslow', zone='Zone 6', lat=51.44784, lng=-0.41028, stype='transport_hub', anchors=[('Feltham', 'ORR')]),
 dict(id='brentwood', name='Brentwood station area', borough='Brentwood', zone='Zone 9', lat=51.6136, lng=0.29959, stype='transport_hub', anchors=[('Brentwood', 'AC')]),
 dict(id='raynes-park', name='Raynes Park station area', borough='Merton', zone='Zone 4', lat=51.40897, lng=-0.23054, stype='transport_hub', anchors=[('Raynes Park', 'ORR')]),
 dict(id='hampstead-heath', name='Hampstead Heath station area', borough='Camden', zone='Zone 2', lat=51.55524, lng=-0.16539, stype='transport_hub', anchors=[('Hampstead Heath', 'AC')]),
 dict(id='epping', name='Epping station area', borough='Epping Forest', zone='Zone 6', lat=51.69368, lng=0.11377, stype='transport_hub', anchors=[('Epping', 'AC')]),
 dict(id='hyde-park-corner', name='Hyde Park Corner station area', borough='Westminster', zone='Zone 1', lat=51.50273, lng=-0.15432, stype='transport_hub', anchors=[('Hyde Park Corner', 'AC')]),
 dict(id='new-malden', name='New Malden station area', borough='Kingston upon Thames', zone='Zone 4', lat=51.40396, lng=-0.25576, stype='transport_hub', anchors=[('New Malden', 'ORR')]),
 dict(id='hither-green', name='Hither Green station area', borough='Lewisham', zone='Zone 3', lat=51.45159, lng=-0.00065, stype='transport_hub', anchors=[('Hither Green', 'ORR')]),
 dict(id='lancaster-gate', name='Lancaster Gate station area', borough='Westminster', zone='Zone 1', lat=51.51184, lng=-0.17538, stype='transport_hub', anchors=[('Lancaster Gate', 'AC')]),
 dict(id='purley', name='Purley station area', borough='Croydon', zone='Zone 6', lat=51.33748, lng=-0.11391, stype='transport_hub', anchors=[('Purley', 'ORR')]),
 dict(id='streatham-common', name='Streatham Common station area', borough='Lambeth', zone='Zone 3', lat=51.41857, lng=-0.13593, stype='transport_hub', anchors=[('Streatham Common', 'ORR')]),
 dict(id='loughton', name='Loughton station area', borough='Epping Forest', zone='Zone 6', lat=51.64144, lng=0.05548, stype='transport_hub', anchors=[('Loughton', 'AC')]),
 dict(id='gospel-oak', name='Gospel Oak station area', borough='Camden', zone='Zone 2', lat=51.55549, lng=-0.15158, stype='transport_hub', anchors=[('Gospel Oak', 'AC')]),
 dict(id='sidcup', name='Sidcup station area', borough='Bexley', zone='Zone 5', lat=51.43402, lng=0.10343, stype='transport_hub', anchors=[('Sidcup', 'ORR')]),
 dict(id='catford-bridge', name='Catford Bridge station area', borough='Lewisham', zone='Zone 3', lat=51.44459, lng=-0.02492, stype='transport_hub', anchors=[('Catford Bridge', 'ORR')]),
 dict(id='streatham-greater-london', name='Streatham station area', borough='Lambeth', zone='Zone 3', lat=51.42596, lng=-0.13131, stype='transport_hub', anchors=[('Streatham (Greater London)', 'ORR')]),
 dict(id='herne-hill', name='Herne Hill station area', borough='Lambeth', zone='Zones 2/3', lat=51.45347, lng=-0.10228, stype='transport_hub', anchors=[('Herne Hill', 'ORR')]),
 dict(id='thornton-heath', name='Thornton Heath station area', borough='Croydon', zone='Zone 4', lat=51.39894, lng=-0.10052, stype='transport_hub', anchors=[('Thornton Heath', 'ORR')]),
 dict(id='kensington-olympia', name='Kensington station area', borough='Kensington and Chelsea', zone='Zone 2', lat=51.49744, lng=-0.20949, stype='transport_hub', anchors=[('Kensington (Olympia)', 'AC')]),
 dict(id='bushey', name='Bushey station area', borough='Watford', zone='Outside zones 1-9', lat=51.64558, lng=-0.38475, stype='transport_hub', anchors=[('Bushey', 'AC')]),
 dict(id='island-gardens', name='Island Gardens station area', borough='Tower Hamlets', zone='Zone 2', lat=51.48807, lng=-0.01051, stype='transport_hub', anchors=[('Island Gardens', 'AC')]),
 dict(id='norbury', name='Norbury station area', borough='Croydon', zone='Zone 3', lat=51.41137, lng=-0.1218, stype='transport_hub', anchors=[('Norbury', 'ORR')]),
 dict(id='grove-park', name='Grove Park station area', borough='Lewisham', zone='Zone 4', lat=51.43077, lng=0.02202, stype='transport_hub', anchors=[('Grove Park', 'ORR')]),
 dict(id='blackheath', name='Blackheath station area', borough='Lewisham', zone='Zone 3', lat=51.4658, lng=0.00892, stype='transport_hub', anchors=[('Blackheath', 'ORR')]),
 dict(id='norbiton', name='Norbiton station area', borough='Kingston upon Thames', zone='Zone 5', lat=51.41231, lng=-0.28408, stype='transport_hub', anchors=[('Norbiton', 'ORR')]),
 dict(id='finchley-road-and-frognal', name='Finchley Road & Frognal station area', borough='Camden', zone='Zone 2', lat=51.55011, lng=-0.18358, stype='transport_hub', anchors=[('Finchley Road & Frognal', 'AC')]),
 dict(id='barnes', name='Barnes station area', borough='Richmond upon Thames', zone='Zone 3', lat=51.46678, lng=-0.24118, stype='transport_hub', anchors=[('Barnes', 'ORR')]),
 dict(id='devons-road', name='Devons Road station area', borough='Tower Hamlets', zone='Zone 2', lat=51.52221, lng=-0.01727, stype='transport_hub', anchors=[('Devons Road', 'AC')]),
 dict(id='royal-oak', name='Royal Oak station area', borough='Westminster', zone='Zone 2', lat=51.51902, lng=-0.18744, stype='transport_hub', anchors=[('Royal Oak', 'AC')]),
 dict(id='battersea-park', name='Battersea Park station area', borough='Wandsworth', zone='Zone 2', lat=51.47761, lng=-0.14758, stype='transport_hub', anchors=[('Battersea Park', 'ORR')]),
 dict(id='tulse-hill', name='Tulse Hill station area', borough='Lambeth', zone='Zone 3', lat=51.43993, lng=-0.10485, stype='transport_hub', anchors=[('Tulse Hill', 'ORR')]),
 dict(id='buckhurst-hill', name='Buckhurst Hill station area', borough='Epping Forest', zone='Zone 5', lat=51.6266, lng=0.04676, stype='transport_hub', anchors=[('Buckhurst Hill', 'AC')]),
 dict(id='latimer-road', name='Latimer Road station area', borough='Kensington and Chelsea', zone='Zone 2', lat=51.51347, lng=-0.21779, stype='transport_hub', anchors=[('Latimer Road', 'AC')]),
 dict(id='royal-victoria', name='Royal Victoria station area', borough='Newham', zone='Zone 3', lat=51.50912, lng=0.01759, stype='transport_hub', anchors=[('Royal Victoria', 'AC')]),
 dict(id='arsenal', name='Arsenal station area', borough='Islington', zone='Zone 2', lat=51.55838, lng=-0.10749, stype='transport_hub', anchors=[('Arsenal', 'AC')]),
 dict(id='south-ealing', name='South Ealing station area', borough='Ealing', zone='Zone 3', lat=51.50086, lng=-0.30768, stype='transport_hub', anchors=[('South Ealing', 'AC')]),
 dict(id='new-eltham', name='New Eltham station area', borough='Greenwich', zone='Zone 4', lat=51.43801, lng=0.07095, stype='transport_hub', anchors=[('New Eltham', 'ORR')]),
 dict(id='bruce-grove', name='Bruce Grove station area', borough='Haringey', zone='Zone 3', lat=51.59371, lng=-0.07, stype='transport_hub', anchors=[('Bruce Grove', 'AC')]),
 dict(id='coulsdon-south', name='Coulsdon South station area', borough='Croydon', zone='Zone 6', lat=51.31554, lng=-0.13797, stype='transport_hub', anchors=[('Coulsdon South', 'ORR')]),
 dict(id='debden', name='Debden station area', borough='Epping Forest', zone='Zone 6', lat=51.64539, lng=0.08378, stype='transport_hub', anchors=[('Debden', 'AC')]),
 dict(id='mill-hill-broadway', name='Mill Hill Broadway station area', borough='Barnet', zone='Zone 4', lat=51.61267, lng=-0.2488, stype='transport_hub', anchors=[('Mill Hill Broadway', 'ORR')]),
 dict(id='rickmansworth', name='Rickmansworth station area', borough='Three Rivers', zone='Zone 7', lat=51.64025, lng=-0.47327, stype='transport_hub', anchors=[('Rickmansworth', 'AC')]),
 dict(id='alexandra-palace', name='Alexandra Palace station area', borough='Haringey', zone='Zone 3', lat=51.5982, lng=-0.12066, stype='transport_hub', anchors=[('Alexandra Palace', 'ORR')]),
 dict(id='streatham-hill', name='Streatham Hill station area', borough='Lambeth', zone='Zone 3', lat=51.43833, lng=-0.12779, stype='transport_hub', anchors=[('Streatham Hill', 'ORR')]),
 dict(id='eltham', name='Eltham station area', borough='Greenwich', zone='Zone 4', lat=51.45559, lng=0.05227, stype='transport_hub', anchors=[('Eltham', 'ORR')]),
 dict(id='teddington', name='Teddington station area', borough='Richmond upon Thames', zone='Zone 6', lat=51.42447, lng=-0.33257, stype='transport_hub', anchors=[('Teddington', 'ORR')]),
 dict(id='watford', name='Watford station area', borough='Watford', zone='Zone 7', lat=51.65745, lng=-0.41738, stype='transport_hub', anchors=[('Watford', 'AC')]),
 dict(id='petts-wood', name='Petts Wood station area', borough='Bromley', zone='Zone 5', lat=51.38863, lng=0.07456, stype='transport_hub', anchors=[('Petts Wood', 'ORR')]),
 dict(id='beckenham-junction', name='Beckenham Junction station area', borough='Bromley', zone='Zone 4', lat=51.41106, lng=-0.02599, stype='transport_hub', anchors=[('Beckenham Junction', 'ORR')]),
 dict(id='kenton', name='Kenton station area', borough='Brent', zone='Zone 4', lat=51.58152, lng=-0.31664, stype='transport_hub', anchors=[('Kenton', 'AC')]),
 dict(id='hornsey', name='Hornsey station area', borough='Haringey', zone='Zone 3', lat=51.58632, lng=-0.11168, stype='transport_hub', anchors=[('Hornsey', 'ORR')]),
 dict(id='st-james-street', name='St James Street station area', borough='Waltham Forest', zone='Zone 3', lat=51.58117, lng=-0.0322, stype='transport_hub', anchors=[('St James Street', 'AC')]),
 dict(id='gallions-reach', name='Gallions Reach station area', borough='Newham', zone='Zone 3', lat=51.50896, lng=0.07179, stype='transport_hub', anchors=[('Gallions Reach', 'AC')]),
 dict(id='deptford-2', name='Deptford station area', borough='Lewisham', zone='Zone 2', lat=51.47898, lng=-0.02663, stype='transport_hub', anchors=[('Deptford', 'ORR')]),
 dict(id='kidbrooke', name='Kidbrooke station area', borough='Greenwich', zone='Zone 3', lat=51.46203, lng=0.0279, stype='transport_hub', anchors=[('Kidbrooke', 'ORR')]),
 dict(id='wallington', name='Wallington station area', borough='Sutton', zone='Zone 5', lat=51.36024, lng=-0.15059, stype='transport_hub', anchors=[('Wallington', 'ORR')]),
 dict(id='palmers-green', name='Palmers Green station area', borough='Enfield', zone='Zone 4', lat=51.61866, lng=-0.11017, stype='transport_hub', anchors=[('Palmers Green', 'ORR')]),
 dict(id='mudchute', name='Mudchute station area', borough='Tower Hamlets', zone='Zone 2', lat=51.49152, lng=-0.01491, stype='transport_hub', anchors=[('Mudchute', 'AC')]),
 dict(id='mortlake', name='Mortlake station area', borough='Richmond upon Thames', zone='Zone 3', lat=51.46806, lng=-0.26737, stype='transport_hub', anchors=[('Mortlake', 'ORR')]),
 dict(id='welling', name='Welling station area', borough='Bexley', zone='Zone 4', lat=51.46482, lng=0.10163, stype='transport_hub', anchors=[('Welling', 'ORR')]),
 dict(id='king-george-v', name='King George V station area', borough='Newham', zone='Zone 3', lat=51.50201, lng=0.06235, stype='transport_hub', anchors=[('King George V', 'AC')]),
 dict(id='rainham-essex', name='Rainham station area', borough='Havering', zone='Zone 6', lat=51.51672, lng=0.19062, stype='transport_hub', anchors=[('Rainham (Essex)', 'ORR')]),
 dict(id='rotherhithe', name='Rotherhithe station area', borough='Southwark', zone='Zone 2', lat=51.50082, lng=-0.05197, stype='transport_hub', anchors=[('Rotherhithe', 'AC')]),
 dict(id='west-norwood', name='West Norwood station area', borough='Lambeth', zone='Zone 3', lat=51.43163, lng=-0.10349, stype='transport_hub', anchors=[('West Norwood', 'ORR')]),
 dict(id='lee-london', name='Lee station area', borough='Lewisham', zone='Zone 2', lat=51.44969, lng=0.01437, stype='transport_hub', anchors=[('Lee (London)', 'ORR')]),
 dict(id='north-harrow', name='North Harrow station area', borough='Harrow', zone='Zone 5', lat=51.58516, lng=-0.36318, stype='transport_hub', anchors=[('North Harrow', 'AC')]),
 dict(id='bexleyheath', name='Bexleyheath station area', borough='Bexley', zone='Zone 5', lat=51.46357, lng=0.13295, stype='transport_hub', anchors=[('Bexleyheath', 'ORR')]),
 dict(id='northwood-hills', name='Northwood Hills station area', borough='Hillingdon', zone='Zone 6', lat=51.60015, lng=-0.40846, stype='transport_hub', anchors=[('Northwood Hills', 'AC')]),
 dict(id='enfield-lock', name='Enfield Lock station area', borough='Enfield', zone='Zone 6', lat=51.67061, lng=-0.02857, stype='transport_hub', anchors=[('Enfield Lock', 'ORR')]),
 dict(id='leytonstone-high-road', name='Leytonstone High Road station area', borough='Waltham Forest', zone='Zone 3', lat=51.56368, lng=0.0082, stype='transport_hub', anchors=[('Leytonstone High Road', 'AC')]),
 dict(id='worcester-park', name='Worcester Park station area', borough='Kingston upon Thames', zone='Zone 4', lat=51.38143, lng=-0.24496, stype='transport_hub', anchors=[('Worcester Park', 'ORR')]),
 dict(id='cockfosters', name='Cockfosters station area', borough='Enfield', zone='Zone 5', lat=51.65137, lng=-0.14852, stype='transport_hub', anchors=[('Cockfosters', 'AC')]),
 dict(id='carpenders-park', name='Carpenders Park station area', borough='Three Rivers', zone='Zone 7', lat=51.62835, lng=-0.38594, stype='transport_hub', anchors=[('Carpenders Park', 'AC')]),
 dict(id='chorleywood', name='Chorleywood station area', borough='Three Rivers', zone='Zone 7', lat=51.65425, lng=-0.51831, stype='transport_hub', anchors=[('Chorleywood', 'AC')]),
 dict(id='winchmore-hill', name='Winchmore Hill station area', borough='Enfield', zone='Zone 4', lat=51.63407, lng=-0.10094, stype='transport_hub', anchors=[('Winchmore Hill', 'ORR')]),
 dict(id='west-ruislip', name='West Ruislip station area', borough='Hillingdon', zone='Zone 6', lat=51.5695, lng=-0.43705, stype='transport_hub', anchors=[('West Ruislip', 'AC')]),
 dict(id='watford-high-street', name='Watford High Street station area', borough='Watford', zone='Zone 8', lat=51.65266, lng=-0.39171, stype='transport_hub', anchors=[('Watford High Street', 'AC')]),
 dict(id='gipsy-hill', name='Gipsy Hill station area', borough='Southwark', zone='Zone 3', lat=51.42453, lng=-0.08404, stype='transport_hub', anchors=[('Gipsy Hill', 'ORR')]),
 dict(id='maze-hill', name='Maze Hill station area', borough='Greenwich', zone='Zone 3', lat=51.48265, lng=0.00375, stype='transport_hub', anchors=[('Maze Hill', 'ORR')]),
 dict(id='north-wembley', name='North Wembley station area', borough='Brent', zone='Zone 4', lat=51.5624, lng=-0.30387, stype='transport_hub', anchors=[('North Wembley', 'AC')]),
 dict(id='mottingham', name='Mottingham station area', borough='Greenwich', zone='Zone 4', lat=51.44025, lng=0.04996, stype='transport_hub', anchors=[('Mottingham', 'ORR')]),
 dict(id='ruislip', name='Ruislip station area', borough='Hillingdon', zone='Zone 6', lat=51.5714, lng=-0.42134, stype='transport_hub', anchors=[('Ruislip', 'AC')]),
 dict(id='ruislip-manor', name='Ruislip Manor station area', borough='Hillingdon', zone='Zone 6', lat=51.5734, lng=-0.4118, stype='transport_hub', anchors=[('Ruislip Manor', 'AC')]),
 dict(id='west-finchley', name='West Finchley station area', borough='Barnet', zone='Zone 4', lat=51.60943, lng=-0.18833, stype='transport_hub', anchors=[('West Finchley', 'AC')]),
 dict(id='east-dulwich-2', name='East Dulwich station area', borough='Southwark', zone='Zone 2', lat=51.46104, lng=-0.0808, stype='transport_hub', anchors=[('East Dulwich', 'ORR')]),
 dict(id='st-mary-cray', name='St Mary Cray station area', borough='Bromley', zone='Zone 6', lat=51.39474, lng=0.10572, stype='transport_hub', anchors=[('St Mary Cray', 'ORR')]),
 dict(id='hillingdon', name='Hillingdon station area', borough='Hillingdon', zone='Zone 6', lat=51.5536, lng=-0.45046, stype='transport_hub', anchors=[('Hillingdon', 'AC')]),
 dict(id='mitcham-eastfields', name='Mitcham Eastfields station area', borough='Merton', zone='Zone 3', lat=51.4074, lng=-0.15487, stype='transport_hub', anchors=[('Mitcham Eastfields', 'ORR')]),
 dict(id='blackwall', name='Blackwall station area', borough='Tower Hamlets', zone='Zone 2', lat=51.50794, lng=-0.00718, stype='transport_hub', anchors=[('Blackwall', 'AC')]),
 dict(id='brondesbury-park', name='Brondesbury Park station area', borough='Brent', zone='Zone 2', lat=51.54051, lng=-0.21034, stype='transport_hub', anchors=[('Brondesbury Park', 'AC')]),
 dict(id='whitton-london', name='Whitton station area', borough='Richmond upon Thames', zone='Zone 5', lat=51.4495, lng=-0.35778, stype='transport_hub', anchors=[('Whitton (London)', 'ORR')]),
 dict(id='boston-manor', name='Boston Manor station area', borough='Ealing', zone='Zone 4', lat=51.49534, lng=-0.32544, stype='transport_hub', anchors=[('Boston Manor', 'AC')]),
 dict(id='new-barnet', name='New Barnet station area', borough='Barnet', zone='Zone 5', lat=51.64828, lng=-0.17262, stype='transport_hub', anchors=[('New Barnet', 'ORR')]),
 dict(id='charlton', name='Charlton station area', borough='Greenwich', zone='Zone 3', lat=51.48676, lng=0.03081, stype='transport_hub', anchors=[('Charlton', 'ORR')]),
 dict(id='ladywell', name='Ladywell station area', borough='Lewisham', zone='Zone 3', lat=51.45603, lng=-0.01919, stype='transport_hub', anchors=[('Ladywell', 'ORR')]),
 dict(id='elverson-road', name='Elverson Road station area', borough='Lewisham', zone='Zones 2/3', lat=51.46852, lng=-0.01621, stype='transport_hub', anchors=[('Elverson Road', 'AC')]),
 dict(id='penge-east', name='Penge East station area', borough='Bromley', zone='Zone 4', lat=51.41931, lng=-0.05414, stype='transport_hub', anchors=[('Penge East', 'ORR')]),
 dict(id='loughborough-junction', name='Loughborough Junction station area', borough='Lambeth', zone='Zone 2', lat=51.46625, lng=-0.10216, stype='transport_hub', anchors=[('Loughborough Junction', 'ORR')]),
 dict(id='royal-albert', name='Royal Albert station area', borough='Newham', zone='Zone 3', lat=51.5084, lng=0.04588, stype='transport_hub', anchors=[('Royal Albert', 'AC')]),
 dict(id='selhurst', name='Selhurst station area', borough='Croydon', zone='Zone 4', lat=51.39221, lng=-0.08865, stype='transport_hub', anchors=[('Selhurst', 'ORR')]),
 dict(id='anerley', name='Anerley station area', borough='Bromley', zone='Zone 4', lat=51.41258, lng=-0.06549, stype='transport_hub', anchors=[('Anerley', 'AC')]),
 dict(id='west-harrow', name='West Harrow station area', borough='Harrow', zone='Zone 5', lat=51.5796, lng=-0.35314, stype='transport_hub', anchors=[('West Harrow', 'AC')]),
 dict(id='enfield-chase', name='Enfield Chase station area', borough='Enfield', zone='Zone 5', lat=51.65264, lng=-0.09086, stype='transport_hub', anchors=[('Enfield Chase', 'ORR')]),
 dict(id='kew-bridge', name='Kew Bridge station area', borough='Hounslow', zone='Zone 3', lat=51.4895, lng=-0.28723, stype='transport_hub', anchors=[('Kew Bridge', 'ORR')]),
 dict(id='turkey-street', name='Turkey Street station area', borough='Enfield', zone='Zone 6', lat=51.67323, lng=-0.04697, stype='transport_hub', anchors=[('Turkey Street', 'AC')]),
 dict(id='gordon-hill', name='Gordon Hill station area', borough='Enfield', zone='Zone 5', lat=51.66295, lng=-0.09422, stype='transport_hub', anchors=[('Gordon Hill', 'ORR')]),
 dict(id='barkingside', name='Barkingside station area', borough='Redbridge', zone='Zone 4', lat=51.58582, lng=0.08862, stype='transport_hub', anchors=[('Barkingside', 'AC')]),
 dict(id='harringay-2', name='Harringay station area', borough='Haringey', zone='Zone 3', lat=51.57756, lng=-0.10527, stype='transport_hub', anchors=[('Harringay', 'ORR')]),
 dict(id='carshalton', name='Carshalton station area', borough='Sutton', zone='Zone 5', lat=51.36858, lng=-0.16638, stype='transport_hub', anchors=[('Carshalton', 'ORR')]),
 dict(id='brimsdown', name='Brimsdown station area', borough='Enfield', zone='Zone 5', lat=51.65557, lng=-0.03079, stype='transport_hub', anchors=[('Brimsdown', 'ORR')]),
 dict(id='shortlands', name='Shortlands station area', borough='Bromley', zone='Zone 4', lat=51.4059, lng=0.00217, stype='transport_hub', anchors=[('Shortlands', 'ORR')]),
 dict(id='southbury', name='Southbury station area', borough='Enfield', zone='Zone 5', lat=51.64803, lng=-0.05263, stype='transport_hub', anchors=[('Southbury', 'AC')]),
 dict(id='woodgrange-park', name='Woodgrange Park station area', borough='Newham', zone='Zones 3/4', lat=51.54917, lng=0.04473, stype='transport_hub', anchors=[('Woodgrange Park', 'AC')]),
 dict(id='slade-green', name='Slade Green station area', borough='Bexley', zone='Zone 6', lat=51.46767, lng=0.19031, stype='transport_hub', anchors=[('Slade Green', 'ORR')]),
 dict(id='barking-riverside', name='Barking Riverside station area', borough='Barking and Dagenham', zone='Zone 4', lat=51.51956, lng=0.11601, stype='transport_hub', anchors=[('Barking Riverside', 'AC')]),
 dict(id='bexley', name='Bexley station area', borough='Bexley', zone='Zone 6', lat=51.44024, lng=0.14795, stype='transport_hub', anchors=[('Bexley', 'ORR')]),
 dict(id='south-croydon', name='South Croydon station area', borough='Croydon', zone='Zone 5', lat=51.36292, lng=-0.09336, stype='transport_hub', anchors=[('South Croydon', 'ORR')]),
 dict(id='crayford', name='Crayford station area', borough='Bexley', zone='Zone 6', lat=51.44818, lng=0.17839, stype='transport_hub', anchors=[('Crayford', 'ORR')]),
 dict(id='west-acton', name='West Acton station area', borough='Ealing', zone='Zone 3', lat=51.51835, lng=-0.28041, stype='transport_hub', anchors=[('West Acton', 'AC')]),
 dict(id='clock-house', name='Clock House station area', borough='Bromley', zone='Zone 4', lat=51.40834, lng=-0.04082, stype='transport_hub', anchors=[('Clock House', 'ORR')]),
 dict(id='stratford-high-street', name='Stratford High Street station area', borough='Newham', zone='Zones 2/3', lat=51.53765, lng=-0.00013, stype='transport_hub', anchors=[('Stratford High Street', 'AC')]),
 dict(id='northumberland-park', name='Northumberland Park station area', borough='Haringey', zone='Zone 3', lat=51.60191, lng=-0.05387, stype='transport_hub', anchors=[('Northumberland Park', 'ORR')]),
 dict(id='hendon', name='Hendon station area', borough='Barnet', zone='Zones 3/4', lat=51.58022, lng=-0.23888, stype='transport_hub', anchors=[('Hendon', 'ORR')]),
 dict(id='south-acton', name='South Acton station area', borough='Ealing', zone='Zone 3', lat=51.49972, lng=-0.2699, stype='transport_hub', anchors=[('South Acton', 'AC')]),
 dict(id='st-margarets-london', name='St Margarets station area', borough='Richmond upon Thames', zone='Zone 4', lat=51.45515, lng=-0.32022, stype='transport_hub', anchors=[('St Margarets (London)', 'ORR')]),
 dict(id='chislehurst', name='Chislehurst station area', borough='Bromley', zone='Zone 5', lat=51.40516, lng=0.05787, stype='transport_hub', anchors=[('Chislehurst', 'ORR')]),
 dict(id='nunhead', name='Nunhead station area', borough='Southwark', zone='Zone 2', lat=51.46684, lng=-0.05237, stype='transport_hub', anchors=[('Nunhead', 'ORR')]),
 dict(id='brentford', name='Brentford station area', borough='Hounslow', zone='Zone 4', lat=51.48766, lng=-0.30968, stype='transport_hub', anchors=[('Brentford', 'ORR')]),
 dict(id='wandsworth-common', name='Wandsworth Common station area', borough='Wandsworth', zone='Zone 3', lat=51.44612, lng=-0.16352, stype='transport_hub', anchors=[('Wandsworth Common', 'ORR')]),
 dict(id='isleworth', name='Isleworth station area', borough='Hounslow', zone='Zone 4', lat=51.47488, lng=-0.3369, stype='transport_hub', anchors=[('Isleworth', 'ORR')]),
 dict(id='barnehurst', name='Barnehurst station area', borough='Bexley', zone='Zone 6', lat=51.46502, lng=0.15965, stype='transport_hub', anchors=[('Barnehurst', 'ORR')]),
 dict(id='hampton-london', name='Hampton station area', borough='Richmond upon Thames', zone='Zone 6', lat=51.41591, lng=-0.37216, stype='transport_hub', anchors=[('Hampton (London)', 'ORR')]),
 dict(id='hayes-kent', name='Hayes station area', borough='Bromley', zone='Zone 5', lat=51.3766, lng=0.00951, stype='transport_hub', anchors=[('Hayes (Kent)', 'ORR')]),
 dict(id='cheam', name='Cheam station area', borough='Sutton', zone='Zone 5', lat=51.35566, lng=-0.21451, stype='transport_hub', anchors=[('Cheam', 'ORR')]),
 dict(id='westcombe-park', name='Westcombe Park station area', borough='Greenwich', zone='Zone 3', lat=51.48424, lng=0.01862, stype='transport_hub', anchors=[('Westcombe Park', 'ORR')]),
 dict(id='elmstead-woods', name='Elmstead Woods station area', borough='Bromley', zone='Zone 4', lat=51.4168, lng=0.04466, stype='transport_hub', anchors=[('Elmstead Woods', 'ORR')]),
 dict(id='oakleigh-park', name='Oakleigh Park station area', borough='Barnet', zone='Zone 4', lat=51.63767, lng=-0.16623, stype='transport_hub', anchors=[('Oakleigh Park', 'ORR')]),
 dict(id='plumstead', name='Plumstead station area', borough='Greenwich', zone='Zone 4', lat=51.48977, lng=0.08402, stype='transport_hub', anchors=[('Plumstead', 'ORR')]),
 dict(id='new-southgate', name='New Southgate station area', borough='Barnet', zone='Zone 4', lat=51.6138, lng=-0.14281, stype='transport_hub', anchors=[('New Southgate', 'ORR')]),
 dict(id='hackbridge', name='Hackbridge station area', borough='Sutton', zone='Zone 4', lat=51.37803, lng=-0.15372, stype='transport_hub', anchors=[('Hackbridge', 'ORR')]),
 dict(id='south-kenton', name='South Kenton station area', borough='Brent', zone='Zone 4', lat=51.57008, lng=-0.30837, stype='transport_hub', anchors=[('South Kenton', 'AC')]),
 dict(id='fairlop', name='Fairlop station area', borough='Redbridge', zone='Zone 4', lat=51.59595, lng=0.09113, stype='transport_hub', anchors=[('Fairlop', 'AC')]),
 dict(id='wembley-stadium', name='Wembley Stadium station area', borough='Brent', zone='Zone 4', lat=51.55425, lng=-0.28477, stype='transport_hub', anchors=[('Wembley Stadium', 'ORR')]),
 dict(id='ponders-end', name='Ponders End station area', borough='Enfield', zone='Zone 5', lat=51.64285, lng=-0.03479, stype='transport_hub', anchors=[('Ponders End', 'ORR')]),
 dict(id='lea-bridge', name='Lea Bridge station area', borough='Waltham Forest', zone='Zone 3', lat=51.56675, lng=-0.03712, stype='transport_hub', anchors=[('Lea Bridge', 'ORR')]),
 dict(id='croxley', name='Croxley station area', borough='Three Rivers', zone='Zone 7', lat=51.64704, lng=-0.44172, stype='transport_hub', anchors=[('Croxley', 'AC')]),
 dict(id='barnes-bridge', name='Barnes Bridge station area', borough='Richmond upon Thames', zone='Zone 3', lat=51.47201, lng=-0.25263, stype='transport_hub', anchors=[('Barnes Bridge', 'ORR')]),
 dict(id='syon-lane', name='Syon Lane station area', borough='Hounslow', zone='Zone 4', lat=51.48181, lng=-0.32478, stype='transport_hub', anchors=[('Syon Lane', 'ORR')]),
 dict(id='west-dulwich', name='West Dulwich station area', borough='Southwark', zone='Zone 3', lat=51.44029, lng=-0.09089, stype='transport_hub', anchors=[('West Dulwich', 'ORR')]),
 dict(id='cricklewood', name='Cricklewood station area', borough='Barnet', zone='Zone 3', lat=51.55875, lng=-0.21297, stype='transport_hub', anchors=[('Cricklewood', 'ORR')]),
 dict(id='hounslow', name='Hounslow station area', borough='Hounslow', zone='Zone 5', lat=51.4621, lng=-0.36173, stype='transport_hub', anchors=[('Hounslow', 'ORR')]),
 dict(id='sanderstead', name='Sanderstead station area', borough='Croydon', zone='Zone 6', lat=51.34839, lng=-0.09346, stype='transport_hub', anchors=[('Sanderstead', 'ORR')]),
 dict(id='st-johns-london', name='St Johns station area', borough='Lewisham', zone='Zone 2', lat=51.46909, lng=-0.02218, stype='transport_hub', anchors=[('St Johns (London)', 'ORR')]),
 dict(id='upminster-bridge', name='Upminster Bridge station area', borough='Havering', zone='Zone 6', lat=51.55826, lng=0.23477, stype='transport_hub', anchors=[('Upminster Bridge', 'AC')]),
 dict(id='ruislip-gardens', name='Ruislip Gardens station area', borough='Hillingdon', zone='Zone 5', lat=51.56066, lng=-0.41046, stype='transport_hub', anchors=[('Ruislip Gardens', 'AC')]),
 dict(id='falconwood', name='Falconwood station area', borough='Bexley', zone='Zone 4', lat=51.45923, lng=0.0793, stype='transport_hub', anchors=[('Falconwood', 'ORR')]),
 dict(id='motspur-park', name='Motspur Park station area', borough='Merton', zone='Zone 4', lat=51.39487, lng=-0.23961, stype='transport_hub', anchors=[('Motspur Park', 'ORR')]),
 dict(id='ickenham', name='Ickenham station area', borough='Hillingdon', zone='Zone 6', lat=51.56157, lng=-0.44235, stype='transport_hub', anchors=[('Ickenham', 'AC')]),
 dict(id='kent-house', name='Kent House station area', borough='Bromley', zone='Zone 4', lat=51.41228, lng=-0.04521, stype='transport_hub', anchors=[('Kent House', 'ORR')]),
 dict(id='hampton-wick', name='Hampton Wick station area', borough='Richmond upon Thames', zone='Zone 6', lat=51.41456, lng=-0.31235, stype='transport_hub', anchors=[('Hampton Wick', 'ORR')]),
 dict(id='penge-west', name='Penge West station area', borough='Bromley', zone='Zone 4', lat=51.4175, lng=-0.06066, stype='transport_hub', anchors=[('Penge West', 'AC')]),
 dict(id='moor-park', name='Moor Park station area', borough='Three Rivers', zone='Zones 6/7', lat=51.62985, lng=-0.43245, stype='transport_hub', anchors=[('Moor Park', 'AC')]),
 dict(id='hatch-end', name='Hatch End station area', borough='Harrow', zone='Zone 6', lat=51.60958, lng=-0.36878, stype='transport_hub', anchors=[('Hatch End', 'AC')]),
 dict(id='tooting-2', name='Tooting station area', borough='Merton', zone='Zone 3', lat=51.41985, lng=-0.16132, stype='transport_hub', anchors=[('Tooting', 'ORR')]),
 dict(id='elmers-end', name='Elmers End station area', borough='Bromley', zone='Zone 4', lat=51.39801, lng=-0.0497, stype='transport_hub', anchors=[('Elmers End', 'ORR')]),
 dict(id='west-wickham', name='West Wickham station area', borough='Bromley', zone='Zone 5', lat=51.38151, lng=-0.01473, stype='transport_hub', anchors=[('West Wickham', 'ORR')]),
 dict(id='carshalton-beeches', name='Carshalton Beeches station area', borough='Sutton', zone='Zone 5', lat=51.3572, lng=-0.16935, stype='transport_hub', anchors=[('Carshalton Beeches', 'ORR')]),
 dict(id='lower-sydenham', name='Lower Sydenham station area', borough='Bromley', zone='Zone 4', lat=51.42475, lng=-0.0333, stype='transport_hub', anchors=[('Lower Sydenham', 'ORR')]),
 dict(id='albany-park', name='Albany Park station area', borough='Bexley', zone='Zone 5', lat=51.43538, lng=0.12596, stype='transport_hub', anchors=[('Albany Park', 'ORR')]),
 dict(id='erith', name='Erith station area', borough='Bexley', zone='Zone 6', lat=51.48158, lng=0.17519, stype='transport_hub', anchors=[('Erith', 'ORR')]),
 dict(id='bickley', name='Bickley station area', borough='Bromley', zone='Zone 5', lat=51.40006, lng=0.04434, stype='transport_hub', anchors=[('Bickley', 'ORR')]),
 dict(id='north-dulwich', name='North Dulwich station area', borough='Southwark', zone='Zones 2/3', lat=51.45418, lng=-0.08833, stype='transport_hub', anchors=[('North Dulwich', 'ORR')]),
 dict(id='drayton-park', name='Drayton Park station area', borough='Islington', zone='Zone 2', lat=51.55311, lng=-0.10577, stype='transport_hub', anchors=[('Drayton Park', 'ORR')]),
 dict(id='headstone-lane', name='Headstone Lane station area', borough='Harrow', zone='Zone 5', lat=51.60255, lng=-0.35695, stype='transport_hub', anchors=[('Headstone Lane', 'AC')]),
 dict(id='new-beckenham', name='New Beckenham station area', borough='Bromley', zone='Zone 4', lat=51.41694, lng=-0.03521, stype='transport_hub', anchors=[('New Beckenham', 'ORR')]),
 dict(id='theydon-bois', name='Theydon Bois station area', borough='Epping Forest', zone='Zone 6', lat=51.67176, lng=0.10308, stype='transport_hub', anchors=[('Theydon Bois', 'AC')]),
 dict(id='chiswick-2', name='Chiswick station area', borough='Hounslow', zone='Zone 3', lat=51.48115, lng=-0.26817, stype='transport_hub', anchors=[('Chiswick', 'ORR')]),
 dict(id='crofton-park', name='Crofton Park station area', borough='Lewisham', zone='Zone 3', lat=51.45522, lng=-0.03663, stype='transport_hub', anchors=[('Crofton Park', 'ORR')]),
 dict(id='essex-road-2', name='Essex Road station area', borough='Islington', zone='Zone 2', lat=51.54073, lng=-0.09619, stype='transport_hub', anchors=[('Essex Road', 'ORR')]),
 dict(id='belvedere', name='Belvedere station area', borough='Bexley', zone='Zone 5', lat=51.49223, lng=0.15337, stype='transport_hub', anchors=[('Belvedere', 'ORR')]),
 dict(id='sydenham-hill', name='Sydenham Hill station area', borough='Southwark', zone='Zone 3', lat=51.43261, lng=-0.08015, stype='transport_hub', anchors=[('Sydenham Hill', 'ORR')]),
 dict(id='strawberry-hill', name='Strawberry Hill station area', borough='Richmond upon Thames', zone='Zone 5', lat=51.43919, lng=-0.33933, stype='transport_hub', anchors=[('Strawberry Hill', 'ORR')]),
 dict(id='brent-cross-west', name='Brent Cross West station area', borough='Barnet', zone='Zone 3', lat=51.56882, lng=-0.22654, stype='transport_hub', anchors=[('Brent Cross West', 'ORR')]),
 dict(id='south-hampstead', name='South Hampstead station area', borough='Camden', zone='Zone 2', lat=51.54143, lng=-0.1788, stype='transport_hub', anchors=[('South Hampstead', 'AC')]),
 dict(id='south-bermondsey', name='South Bermondsey station area', borough='Southwark', zone='Zone 2', lat=51.48795, lng=-0.05446, stype='transport_hub', anchors=[('South Bermondsey', 'ORR')]),
 dict(id='bellingham', name='Bellingham station area', borough='Lewisham', zone='Zone 3', lat=51.43283, lng=-0.01952, stype='transport_hub', anchors=[('Bellingham', 'ORR')]),
 dict(id='waddon', name='Waddon station area', borough='Croydon', zone='Zone 5', lat=51.36733, lng=-0.11743, stype='transport_hub', anchors=[('Waddon', 'ORR')]),
 dict(id='chelsfield', name='Chelsfield station area', borough='Bromley', zone='Zone 6', lat=51.35661, lng=0.10833, stype='transport_hub', anchors=[('Chelsfield', 'ORR')]),
 dict(id='tolworth', name='Tolworth station area', borough='Kingston upon Thames', zone='Zone 5', lat=51.37687, lng=-0.27944, stype='transport_hub', anchors=[('Tolworth', 'ORR')]),
 dict(id='eden-park', name='Eden Park station area', borough='Bromley', zone='Zone 5', lat=51.39018, lng=-0.02637, stype='transport_hub', anchors=[('Eden Park', 'ORR')]),
 dict(id='north-ealing', name='North Ealing station area', borough='Ealing', zone='Zone 3', lat=51.51749, lng=-0.28875, stype='transport_hub', anchors=[('North Ealing', 'AC')]),
 dict(id='meridian-water', name='Meridian Water station area', borough='Enfield', zone='Zone 4', lat=51.61, lng=-0.05008, stype='transport_hub', anchors=[('Meridian Water', 'ORR')]),
 dict(id='grange-park', name='Grange Park station area', borough='Enfield', zone='Zone 5', lat=51.64333, lng=-0.09694, stype='transport_hub', anchors=[('Grange Park', 'ORR')]),
 dict(id='chessington-north', name='Chessington North station area', borough='Kingston upon Thames', zone='Zone 6', lat=51.36398, lng=-0.30073, stype='transport_hub', anchors=[('Chessington North', 'ORR')]),
 dict(id='malden-manor', name='Malden Manor station area', borough='Kingston upon Thames', zone='Zone 4', lat=51.38473, lng=-0.26125, stype='transport_hub', anchors=[('Malden Manor', 'ORR')]),
 dict(id='purley-oaks', name='Purley Oaks station area', borough='Croydon', zone='Zone 6', lat=51.34703, lng=-0.09871, stype='transport_hub', anchors=[('Purley Oaks', 'ORR')]),
 dict(id='fulwell', name='Fulwell station area', borough='Richmond upon Thames', zone='Zone 6', lat=51.43391, lng=-0.34906, stype='transport_hub', anchors=[('Fulwell', 'ORR')]),
 dict(id='beckton-park', name='Beckton Park station area', borough='Newham', zone='Zone 3', lat=51.50876, lng=0.05494, stype='transport_hub', anchors=[('Beckton Park', 'AC')]),
 dict(id='dagenham-dock', name='Dagenham Dock station area', borough='Barking and Dagenham', zone='Zone 5', lat=51.52619, lng=0.14543, stype='transport_hub', anchors=[('Dagenham Dock', 'ORR')]),
 dict(id='mitcham-junction', name='Mitcham Junction station area', borough='Merton', zone='Zone 4', lat=51.39294, lng=-0.15778, stype='transport_hub', anchors=[('Mitcham Junction', 'ORR')]),
 dict(id='beckenham-hill', name='Beckenham Hill station area', borough='Lewisham', zone='Zone 4', lat=51.42452, lng=-0.01591, stype='transport_hub', anchors=[('Beckenham Hill', 'ORR')]),
 dict(id='grange-hill', name='Grange Hill station area', borough='Redbridge', zone='Zone 4', lat=51.61313, lng=0.0925, stype='transport_hub', anchors=[('Grange Hill', 'AC')]),
 dict(id='berrylands', name='Berrylands station area', borough='Kingston upon Thames', zone='Zone 5', lat=51.39901, lng=-0.28091, stype='transport_hub', anchors=[('Berrylands', 'ORR')]),
 dict(id='hadley-wood', name='Hadley Wood station area', borough='Enfield', zone='Zone 6', lat=51.66863, lng=-0.17614, stype='transport_hub', anchors=[('Hadley Wood', 'ORR')]),
 dict(id='chessington-south', name='Chessington South station area', borough='Kingston upon Thames', zone='Zone 6', lat=51.35675, lng=-0.3081, stype='transport_hub', anchors=[('Chessington South', 'ORR')]),
 dict(id='north-sheen', name='North Sheen station area', borough='Richmond upon Thames', zone='Zone 3', lat=51.46532, lng=-0.28658, stype='transport_hub', anchors=[('North Sheen', 'ORR')]),
 dict(id='haydons-road', name='Haydons Road station area', borough='Merton', zone='Zone 3', lat=51.42536, lng=-0.18834, stype='transport_hub', anchors=[('Haydons Road', 'ORR')]),
 dict(id='woolwich-dockyard', name='Woolwich Dockyard station area', borough='Greenwich', zone='Zone 3', lat=51.49109, lng=0.05488, stype='transport_hub', anchors=[('Woolwich Dockyard', 'ORR')]),
 dict(id='chigwell', name='Chigwell station area', borough='Epping Forest', zone='Zone 4', lat=51.61792, lng=0.07504, stype='transport_hub', anchors=[('Chigwell', 'AC')]),
 dict(id='emerson-park', name='Emerson Park station area', borough='Havering', zone='Zone 6', lat=51.5686, lng=0.22024, stype='transport_hub', anchors=[('Emerson Park', 'AC')]),
 dict(id='riddlesdown', name='Riddlesdown station area', borough='Croydon', zone='Zone 6', lat=51.33293, lng=-0.0997, stype='transport_hub', anchors=[('Riddlesdown', 'ORR')]),
 dict(id='wimbledon-chase', name='Wimbledon Chase station area', borough='Merton', zone='Zone 3', lat=51.41025, lng=-0.21479, stype='transport_hub', anchors=[('Wimbledon Chase', 'ORR')]),
 dict(id='kenley', name='Kenley station area', borough='Croydon', zone='Zone 6', lat=51.32478, lng=-0.10084, stype='transport_hub', anchors=[('Kenley', 'ORR')]),
 dict(id='west-sutton', name='West Sutton station area', borough='Sutton', zone='Zone 5', lat=51.36626, lng=-0.20448, stype='transport_hub', anchors=[('West Sutton', 'ORR')]),
 dict(id='sutton-common', name='Sutton Common station area', borough='Sutton', zone='Zone 4', lat=51.37543, lng=-0.19611, stype='transport_hub', anchors=[('Sutton Common', 'ORR')]),
 dict(id='ravensbourne', name='Ravensbourne station area', borough='Bromley', zone='Zone 4', lat=51.41431, lng=-0.00763, stype='transport_hub', anchors=[('Ravensbourne', 'ORR')]),
 dict(id='bromley-north', name='Bromley North station area', borough='Bromley', zone='Zone 4', lat=51.4092, lng=0.0178, stype='transport_hub', anchors=[('Bromley North', 'ORR')]),
 dict(id='roding-valley', name='Roding Valley station area', borough='Redbridge', zone='Zone 4', lat=51.61708, lng=0.04376, stype='transport_hub', anchors=[('Roding Valley', 'AC')]),
 dict(id='belmont', name='Belmont station area', borough='Sutton', zone='Zone 5', lat=51.3439, lng=-0.19878, stype='transport_hub', anchors=[('Belmont', 'ORR')]),
 dict(id='sundridge-park', name='Sundridge Park station area', borough='Bromley', zone='Zone 4', lat=51.41396, lng=0.02148, stype='transport_hub', anchors=[('Sundridge Park', 'ORR')]),
 dict(id='knockholt', name='Knockholt station area', borough='Bromley', zone='Zone 6', lat=51.34577, lng=0.13083, stype='transport_hub', anchors=[('Knockholt', 'ORR')]),
 dict(id='northolt-park', name='Northolt Park station area', borough='Harrow', zone='Zone 5', lat=51.55748, lng=-0.35942, stype='transport_hub', anchors=[('Northolt Park', 'ORR')]),
 dict(id='st-helier-london', name='St Helier station area', borough='Merton', zone='Zone 4', lat=51.38945, lng=-0.19886, stype='transport_hub', anchors=[('St Helier (London)', 'ORR')]),
 dict(id='woodmansterne', name='Woodmansterne station area', borough='Croydon', zone='Zone 6', lat=51.31905, lng=-0.15388, stype='transport_hub', anchors=[('Woodmansterne', 'ORR')]),
 dict(id='south-merton', name='South Merton station area', borough='Merton', zone='Zone 4', lat=51.40333, lng=-0.20552, stype='transport_hub', anchors=[('South Merton', 'ORR')]),
 dict(id='crews-hill', name='Crews Hill station area', borough='Enfield', zone='Zone 6', lat=51.68476, lng=-0.10722, stype='transport_hub', anchors=[('Crews Hill', 'ORR')]),
 dict(id='castle-bar-park', name='Castle Bar Park station area', borough='Ealing', zone='Zone 4', lat=51.52287, lng=-0.3315, stype='transport_hub', anchors=[('Castle Bar Park', 'ORR')]),
 dict(id='reedham-london', name='Reedham station area', borough='Croydon', zone='Zone 6', lat=51.33113, lng=-0.12342, stype='transport_hub', anchors=[('Reedham (London)', 'ORR')]),
 dict(id='birkbeck', name='Birkbeck station area', borough='Bromley', zone='Zone 4', lat=51.40346, lng=-0.05654, stype='transport_hub', anchors=[('Birkbeck', 'ORR')]),
 dict(id='coulsdon-town', name='Coulsdon Town station area', borough='Croydon', zone='Zone 6', lat=51.32206, lng=-0.13425, stype='transport_hub', anchors=[('Coulsdon Town', 'ORR')]),
 dict(id='morden-south', name='Morden South station area', borough='Merton', zone='Zone 4', lat=51.39568, lng=-0.19924, stype='transport_hub', anchors=[('Morden South', 'ORR')]),
 dict(id='south-greenford', name='South Greenford station area', borough='Ealing', zone='Zone 4', lat=51.5332, lng=-0.33644, stype='transport_hub', anchors=[('South Greenford', 'ORR')]),
 dict(id='drayton-green', name='Drayton Green station area', borough='Ealing', zone='Zone 4', lat=51.51638, lng=-0.33019, stype='transport_hub', anchors=[('Drayton Green', 'ORR')]),
]
