# New street segments to add (38). Anchors use exact NUMBAT 2024 station names.
NEW_SEGMENTS = [
 dict(id="leather-lane", name="Leather Lane, Holborn", borough="Camden", zone="Zone 1", lat=51.5186, lng=-0.1100, stype="side_street", anchors=[("Chancery Lane","LU"),("Farringdon","LU")]),
 dict(id="maltby-street", name="Maltby Street, Bermondsey", borough="Southwark", zone="Zones 1/2", lat=51.4986, lng=-0.0738, stype="side_street", anchors=[("London Bridge LU","LU"),("Bermondsey","LU")]),
 dict(id="vauxhall", name="Vauxhall Cross", borough="Lambeth", zone="Zones 1/2", lat=51.4860, lng=-0.1240, stype="transport_hub", anchors=[("Vauxhall LU","LU")]),
 dict(id="westbourne-grove", name="Westbourne Grove, Notting Hill", borough="Westminster", zone="Zone 2", lat=51.5152, lng=-0.1976, stype="high_street", anchors=[("Notting Hill Gate","LU"),("Bayswater","LU")]),
 dict(id="fulham-road", name="Fulham Road, Chelsea", borough="Kensington and Chelsea", zone="Zone 2", lat=51.4820, lng=-0.1945, stype="high_street", anchors=[("Fulham Broadway","LU"),("Parsons Green","LU")]),
 dict(id="columbia-road", name="Columbia Road, Bethnal Green", borough="Tower Hamlets", zone="Zone 2", lat=51.5275, lng=-0.0695, stype="side_street", anchors=[("Hoxton","LO"),("Cambridge Heath","LO")]),
 dict(id="broadway-market", name="Broadway Market, London Fields", borough="Hackney", zone="Zone 2", lat=51.5359, lng=-0.0617, stype="high_street", anchors=[("London Fields","LO"),("Cambridge Heath","LO")]),
 dict(id="stoke-newington", name="Stoke Newington Church Street", borough="Hackney", zone="Zone 2", lat=51.5613, lng=-0.0763, stype="high_street", anchors=[("Stoke Newington","LO"),("Rectory Road","LO")]),
 dict(id="bellenden-road", name="Bellenden Road, Peckham", borough="Southwark", zone="Zone 2", lat=51.4616, lng=-0.0716, stype="side_street", anchors=[("Peckham Rye","LO"),("Queens Road Peckham","LO")]),
 dict(id="deptford", name="Deptford High Street", borough="Lewisham", zone="Zone 2", lat=51.4734, lng=-0.0266, stype="high_street", anchors=[("Deptford Bridge","DLR"),("New Cross","LO")]),
 dict(id="new-cross", name="New Cross Road", borough="Lewisham", zone="Zone 2", lat=51.4755, lng=-0.0398, stype="high_street", anchors=[("New Cross","LO"),("New Cross Gate","LO")]),
 dict(id="clapham-old-town", name="The Pavement, Clapham Old Town", borough="Lambeth", zone="Zone 2", lat=51.4622, lng=-0.1398, stype="high_street", anchors=[("Clapham Common","LU"),("Clapham North","LU")]),
 dict(id="battersea-park-road", name="Battersea Park Road", borough="Wandsworth", zone="Zone 2", lat=51.4750, lng=-0.1530, stype="high_street", anchors=[("Battersea Power Station","LU"),("Wandsworth Road","LO")]),
 dict(id="parsons-green", name="Parsons Green", borough="Hammersmith and Fulham", zone="Zone 2", lat=51.4738, lng=-0.2012, stype="side_street", anchors=[("Parsons Green","LU"),("Fulham Broadway","LU")]),
 dict(id="west-hampstead", name="West End Lane, West Hampstead", borough="Camden", zone="Zone 2", lat=51.5467, lng=-0.1912, stype="high_street", anchors=[("West Hampstead LU","LU"),("West Hampstead LO","LO")]),
 dict(id="salusbury-road", name="Salusbury Road, Queen's Park", borough="Brent", zone="Zone 2", lat=51.5348, lng=-0.2047, stype="high_street", anchors=[("Queen's Park","LU"),("Kensal Rise","LO")]),
 dict(id="st-johns-wood", name="St John's Wood High Street", borough="Westminster", zone="Zone 2", lat=51.5340, lng=-0.1723, stype="high_street", anchors=[("St John's Wood","LU"),("Maida Vale","LU")]),
 dict(id="primrose-hill", name="Regent's Park Road, Primrose Hill", borough="Camden", zone="Zone 2", lat=51.5397, lng=-0.1568, stype="side_street", anchors=[("Chalk Farm","LU"),("Camden Town","LU")]),
 dict(id="white-city", name="Wood Lane, White City", borough="Hammersmith and Fulham", zone="Zone 2", lat=51.5118, lng=-0.2240, stype="major_retail", anchors=[("White City","LU"),("Wood Lane","LU")]),
 dict(id="finsbury-park", name="Seven Sisters Road, Finsbury Park", borough="Islington", zone="Zone 2", lat=51.5645, lng=-0.1063, stype="transport_hub", anchors=[("Finsbury Park","LU")]),
 dict(id="highbury-barn", name="Highbury Barn", borough="Islington", zone="Zone 2", lat=51.5520, lng=-0.0976, stype="side_street", anchors=[("Highbury & Islington","LU"),("Canonbury","LO")]),
 dict(id="tufnell-park", name="Fortess Road, Tufnell Park", borough="Islington", zone="Zone 2", lat=51.5567, lng=-0.1377, stype="high_street", anchors=[("Tufnell Park","LU")]),
 dict(id="mile-end", name="Mile End Road", borough="Tower Hamlets", zone="Zone 2", lat=51.5225, lng=-0.0392, stype="high_street", anchors=[("Mile End","LU"),("Stepney Green","LU")]),
 dict(id="hackney-wick", name="White Post Lane, Hackney Wick", borough="Hackney", zone="Zone 2", lat=51.5432, lng=-0.0237, stype="side_street", anchors=[("Hackney Wick","LO"),("Homerton","LO")]),
 dict(id="surrey-quays", name="Surrey Quays", borough="Southwark", zone="Zone 2", lat=51.4943, lng=-0.0474, stype="major_retail", anchors=[("Canada Water","LU"),("Surrey Quays","LO")]),
 dict(id="chrisp-street", name="Chrisp Street Market, Poplar", borough="Tower Hamlets", zone="Zone 2", lat=51.5126, lng=-0.0133, stype="market", anchors=[("Poplar","DLR"),("All Saints","DLR")]),
 dict(id="roman-road", name="Roman Road, Bow", borough="Tower Hamlets", zone="Zones 2/3", lat=51.5279, lng=-0.0245, stype="market", anchors=[("Bow Road","LU"),("Bow Church","DLR")]),
 dict(id="chatsworth-road", name="Chatsworth Road, Homerton", borough="Hackney", zone="Zones 2/3", lat=51.5495, lng=-0.0420, stype="high_street", anchors=[("Homerton","LO"),("Hackney Central","LO")]),
 dict(id="archway", name="Junction Road, Archway", borough="Islington", zone="Zones 2/3", lat=51.5655, lng=-0.1347, stype="transport_hub", anchors=[("Archway","LU"),("Upper Holloway","LO")]),
 dict(id="acton", name="Acton High Street", borough="Ealing", zone="Zone 3", lat=51.5075, lng=-0.2705, stype="high_street", anchors=[("Acton Central","LO"),("Acton Town","LU")]),
 dict(id="seven-sisters", name="Seven Sisters Road, Tottenham", borough="Haringey", zone="Zones 2/3", lat=51.5825, lng=-0.0725, stype="high_street", anchors=[("Seven Sisters","LU"),("South Tottenham","LO")]),
 dict(id="leyton", name="Leyton High Road", borough="Waltham Forest", zone="Zone 3", lat=51.5580, lng=-0.0060, stype="high_street", anchors=[("Leyton","LU"),("Leyton Midland Road","LO")]),
 dict(id="upton-park", name="Green Street, Upton Park", borough="Newham", zone="Zone 3", lat=51.5350, lng=0.0330, stype="high_street", anchors=[("Upton Park","LU"),("Plaistow","LU")]),
 dict(id="canning-town", name="Barking Road, Canning Town", borough="Newham", zone="Zones 2/3", lat=51.5140, lng=0.0130, stype="high_street", anchors=[("Canning Town","LU"),("Custom House EL","EZL")]),
 dict(id="harringay", name="Green Lanes, Harringay", borough="Haringey", zone="Zone 3", lat=51.5772, lng=-0.0980, stype="high_street", anchors=[("Harringay Green Lanes","LO"),("Manor House","LU")]),
 dict(id="highgate", name="Highgate High Street", borough="Haringey", zone="Zone 3", lat=51.5715, lng=-0.1450, stype="side_street", anchors=[("Highgate","LU"),("Archway","LU")]),
 dict(id="denmark-hill", name="Denmark Hill, Camberwell", borough="Southwark", zone="Zone 2", lat=51.4695, lng=-0.0890, stype="transport_hub", anchors=[("Denmark Hill","LO")]),
 dict(id="forest-hill", name="Dartmouth Road, Forest Hill", borough="Lewisham", zone="Zone 3", lat=51.4395, lng=-0.0530, stype="high_street", anchors=[("Forest Hill","LO"),("Honor Oak Park","LO")]),
]
