window.CITY={id:"glasgow",name:"Glasgow",region:"Greater Glasgow",mapCenter:[55.8612,-4.2499],mapZoom:12,texts:{
 flowCredit:"ORR Estimates of Station Usage 2024-25 (National Rail); day-of-week split modelled",
 police:"Police Scotland",
 voaYear:"Mar 2025",
 voaMethod:`<p>Scottish Assessors do not publish rateable value per m². For Glasgow the retail and office £/m² figures are MODELLED: the average rateable value per shop and per office in the assessor area (SAA valuation roll, 2026 revaluation, observed) is scaled to a £/m² estimate using the relationship between average RV per property and £/m² in the Valuation Office Agency 2025 stock-of-properties and floorspace statistics for comparable English cities. The observed SAA averages are shown on each segment's Occupancy cost card.</p>`,
 crimeNote:"Source: Police Scotland recorded offences around the anchor, via data.police.uk. A relative signal between areas, not an absolute risk figure.",
 movement:`<p>Typical-day station entries and exits by day type (Mon / Tue-Thu / Fri / Sat / Sun) and annual totals from ORR Estimates of Station Usage 2024-25 for every National Rail station in Greater Glasgow, summed over the stations named for each segment. ORR publishes annual totals only, so the day-of-week split is MODELLED on a standard GB rail week profile (median London Overground profile) and labelled as such; the annual total stays OBSERVED. Stations within 900 m from OpenStreetMap. Street-level pitches inherit their parent catchment's counts scaled to the street's share of recorded commercial units (marked MODELLED); streets beyond 900 m of any station show no flow at all. Tram/metro stops carry no open stop-level counts, so tram flow is not an anchor in this city.</p>`,
 crimeMethod:`<p>Police Scotland recorded street-level offences within ~450 m of each segment anchor, 12 months to July 2026: shoplifting, theft from the person, robbery and burglary, via data.police.uk. Rates are normalised per 1,000 residents.</p>`,
 crimeDropped:"Police Scotland does not publish street-level recorded crime. Scottish recorded-crime statistics (statistics.gov.scot) are published at council-area level only, so no crime figures are shown for Glasgow anywhere on this page - we drop the field rather than estimate it. Every other data field is unaffected.",
 resNote:"Data Zone ≈ 800 residents (Scottish census geography). It describes residents, not the people walking this street.",
 resMethod:`<p>Census 2022 (Scotland) statistics for the segment anchor: age by single year (UV103), ethnic group (UV201), economic activity and students (UV601) and occupation (UV606) at Data Zone level; country of birth (MV204) at the finer Output Area level. National Records of Scotland bulk tables.</p>`,
 resResolution:"Resolution: Data Zone (~800 residents); born-outside-UK at Output Area level.",

 coverage:(SEGS,UNITS)=>`<p>${SEGS.length.toLocaleString("en-GB")} segments covering Greater Glasgow at street level: ${SEGS.filter(s=>s.lvl!=="street").length} area pitches (every National Rail station catchment in Greater Glasgow plus curated commercial areas - ORR Estimates of Station Usage 2024-25, no minimum flow) and ${SEGS.filter(s=>s.lvl==="street").length.toLocaleString("en-GB")} street pitches - every named retail street and parade with 8 or more recorded commercial units, long streets split into roughly 400 m stretches. ${UNITS.length.toLocaleString("en-GB")} individual commercial units recorded across them. A street pitch inside a station catchment carries that catchment's flow MODELLED down to the street's share of recorded units; a street more than 900 m from any station has no flow anchor and says so on its panel.</p>`,
}};